apiVersion: v1
kind: Service
metadata:
  name: eks-python-api
spec:
  selector:
    app: eks-python-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  